// frontend/src/components/candidates/CandidateDrawer.vue
<template>
  <Teleport to="body">
    <!-- Backdrop -->
    <div
      v-if="modelValue"
      class="fixed inset-0 bg-black/30 z-40 backdrop-blur-sm"
      @click="close"
    />

    <!-- Drawer panel -->
    <div
      :class="[
        'fixed inset-y-0 right-0 z-50 w-full max-w-2xl bg-white shadow-2xl flex flex-col transition-transform duration-300 ease-in-out',
        modelValue ? 'translate-x-0' : 'translate-x-full'
      ]"
    >
      <!-- Header -->
      <div class="flex items-center justify-between px-6 py-4 border-b border-gray-200 flex-shrink-0">
        <div class="flex items-center gap-3">
          <div class="w-10 h-10 rounded-full bg-brand-100 flex items-center justify-center">
            <span class="text-brand-700 font-semibold text-sm">{{ initials }}</span>
          </div>
          <div>
            <h2 class="text-lg font-semibold text-gray-900">{{ candidate?.candidateName }}</h2>
            <p class="text-xs text-gray-500">{{ candidate?.postingName }}</p>
          </div>
        </div>
        <div class="flex items-center gap-2">
          <RouterLink
            :to="`/candidates/${candidate?.id}`"
            class="btn-secondary btn-sm"
            @click="close"
          >
            Full view
          </RouterLink>
          <button class="p-2 rounded-lg hover:bg-gray-100 text-gray-400 hover:text-gray-600" @click="close">
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
      </div>

      <!-- Content -->
      <div class="flex-1 overflow-y-auto">
        <!-- Tabs -->
        <div class="flex border-b border-gray-200 px-6">
          <button
            v-for="tab in tabs"
            :key="tab.id"
            :class="[
              'py-3 px-1 mr-6 text-sm font-medium border-b-2 transition-colors -mb-px',
              activeTab === tab.id
                ? 'border-brand-600 text-brand-600'
                : 'border-transparent text-gray-500 hover:text-gray-700'
            ]"
            @click="activeTab = tab.id"
          >
            {{ tab.label }}
          </button>
        </div>

        <!-- Overview Tab -->
        <div v-if="activeTab === 'overview'" class="p-6 space-y-6">
          <!-- Status + AI Score row -->
          <div class="flex flex-wrap gap-4">
            <div class="flex items-center gap-2">
              <span class="text-sm text-gray-500">Status:</span>
              <StatusBadge :status="candidate?.status" />
            </div>
            <div v-if="candidate?.aiScore != null" class="flex items-center gap-2">
              <span class="text-sm text-gray-500">AI Score:</span>
              <span :class="['text-sm font-bold', scoreColor(candidate.aiScore)]">{{ candidate.aiScore }}%</span>
            </div>
            <div v-if="candidate?.aiRecommendation" class="flex items-center gap-2">
              <span class="text-sm text-gray-500">AI Rec:</span>
              <StatusBadge :status="candidate.aiRecommendation" />
            </div>
          </div>

          <!-- Details grid -->
          <div class="grid grid-cols-2 gap-4">
            <InfoField label="Location" :value="candidate?.location" />
            <InfoField label="Phone" :value="candidate?.phone" />
            <InfoField label="Hiring Manager" :value="candidate?.hiringManager" />
            <InfoField label="Recruiter" :value="candidate?.recruiter" />
            <InfoField label="Date Applied" :value="candidate?.dateApplied" />
            <InfoField label="Received At" :value="formatDate(candidate?.receivedAt)" />
            <InfoField label="Reviewed At" :value="formatDate(candidate?.reviewedAt)" />
            <InfoField label="Called" :value="candidate?.called" />
          </div>

          <!-- AI Summary -->
          <div v-if="candidate?.aiSummary">
            <h4 class="text-sm font-semibold text-gray-700 mb-2">AI Summary</h4>
            <div class="bg-blue-50 rounded-lg p-4 text-sm text-gray-700 leading-relaxed">
              {{ candidate.aiSummary }}
            </div>
          </div>

          <!-- AI Criteria -->
          <div v-if="candidate?.aiCriteriaMet || candidate?.aiCriteriaMissing" class="grid grid-cols-2 gap-4">
            <div v-if="candidate?.aiCriteriaMet">
              <h4 class="text-sm font-semibold text-green-700 mb-2">✓ Criteria Met</h4>
              <div class="bg-green-50 rounded-lg p-3 text-xs text-green-800 leading-relaxed">
                {{ candidate.aiCriteriaMet }}
              </div>
            </div>
            <div v-if="candidate?.aiCriteriaMissing">
              <h4 class="text-sm font-semibold text-red-700 mb-2">✗ Criteria Missing</h4>
              <div class="bg-red-50 rounded-lg p-3 text-xs text-red-800 leading-relaxed">
                {{ candidate.aiCriteriaMissing }}
              </div>
            </div>
          </div>
        </div>

        <!-- Edit Tab -->
        <div v-if="activeTab === 'edit'" class="p-6">
          <form @submit.prevent="saveEdit" class="space-y-4">
            <div class="grid grid-cols-2 gap-4">
              <div>
                <label class="label">Candidate Name</label>
                <input v-model="editForm.candidateName" class="input" />
              </div>
              <div>
                <label class="label">Phone</label>
                <input v-model="editForm.phone" class="input" placeholder="+49 …" />
              </div>
              <div>
                <label class="label">Posting Name</label>
                <input v-model="editForm.postingName" class="input" />
              </div>
              <div>
                <label class="label">Location</label>
                <input v-model="editForm.location" class="input" />
              </div>
              <div>
                <label class="label">Hiring Manager</label>
                <input v-model="editForm.hiringManager" class="input" />
              </div>
              <div>
                <label class="label">Recruiter</label>
                <input v-model="editForm.recruiter" class="input" />
              </div>
              <div>
                <label class="label">Date Applied</label>
                <input v-model="editForm.dateApplied" class="input" type="date" />
              </div>
              <div>
                <label class="label">Status</label>
                <select v-model="editForm.status" class="input">
                  <option v-for="s in STATUSES" :key="s" :value="s">{{ capitalize(s) }}</option>
                </select>
              </div>
            </div>

            <div v-if="editError" class="bg-red-50 border border-red-200 rounded-lg px-4 py-2 text-sm text-red-700">
              {{ editError }}
            </div>
            <div v-if="editSuccess" class="bg-green-50 border border-green-200 rounded-lg px-4 py-2 text-sm text-green-700">
              Changes saved successfully!
            </div>

            <div class="flex gap-3">
              <button type="submit" class="btn-primary" :disabled="saving">
                <svg v-if="saving" class="animate-spin h-4 w-4" fill="none" viewBox="0 0 24 24">
                  <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"/>
                  <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>
                </svg>
                {{ saving ? 'Saving…' : 'Save changes' }}
              </button>
            </div>
          </form>
        </div>

        <!-- Transcript Tab -->
        <div v-if="activeTab === 'transcript'" class="p-6">
          <div v-if="candidate?.transcript">
            <h4 class="text-sm font-semibold text-gray-700 mb-3">Call Transcript</h4>
            <div class="bg-gray-50 rounded-lg p-4 text-sm text-gray-700 leading-relaxed whitespace-pre-wrap font-mono text-xs">{{ candidate.transcript }}</div>
          </div>
          <div v-else class="text-center py-12 text-gray-400">
            <svg class="w-8 h-8 mx-auto mb-2 text-gray-200" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M19 11a7 7 0 01-7 7m0 0a7 7 0 01-7-7m7 7v4m0 0H8m4 0h4m-4-8a3 3 0 01-3-3V5a3 3 0 116 0v6a3 3 0 01-3 3z" />
            </svg>
            No transcript available
          </div>
        </div>
      </div>

      <!-- Footer actions -->
      <div class="border-t border-gray-200 px-6 py-4 flex-shrink-0 flex items-center justify-between">
        <div class="text-xs text-gray-400">
          Added {{ formatDate(candidate?.createdAt) }}
        </div>
        <button
          v-if="isAdmin"
          class="btn-danger btn-sm"
          @click="showDelete = true"
        >
          Delete candidate
        </button>
      </div>
    </div>
  </Teleport>

  <!-- Delete confirm -->
  <ConfirmDialog
    v-model="showDelete"
    title="Delete candidate?"
    :message="`This will permanently delete ${candidate?.candidateName}. This cannot be undone.`"
    confirm-text="Delete"
    :loading="deleting"
    @confirm="deleteCandidate"
  />
</template>

<script setup>
import { ref, reactive, watch, computed } from 'vue'
import { candidatesApi } from '@/api'
import StatusBadge from '@/components/shared/StatusBadge.vue'
import ConfirmDialog from '@/components/shared/ConfirmDialog.vue'

const props = defineProps({
  modelValue: Boolean,
  candidate: Object,
  isAdmin: Boolean,
})
const emit = defineEmits(['update:modelValue', 'updated', 'deleted'])

const activeTab = ref('overview')
const tabs = [
  { id: 'overview', label: 'Overview' },
  { id: 'edit', label: 'Edit' },
  { id: 'transcript', label: 'Transcript' },
]

const STATUSES = ['pending', 'reviewing', 'reviewed', 'called', 'scheduled', 'rejected', 'hired']

const editForm = reactive({
  candidateName: '',
  phone: '',
  postingName: '',
  location: '',
  hiringManager: '',
  recruiter: '',
  dateApplied: '',
  status: '',
})

watch(() => props.candidate, (c) => {
  if (!c) return
  Object.assign(editForm, {
    candidateName: c.candidateName || '',
    phone: c.phone || '',
    postingName: c.postingName || '',
    location: c.location || '',
    hiringManager: c.hiringManager || '',
    recruiter: c.recruiter || '',
    dateApplied: c.dateApplied || '',
    status: c.status || '',
  })
  activeTab.value = 'overview'
}, { immediate: true })

const initials = computed(() => {
  const name = props.candidate?.candidateName || ''
  return name.split(' ').map(n => n[0]).join('').toUpperCase().slice(0, 2)
})

const saving = ref(false)
const editError = ref('')
const editSuccess = ref(false)

async function saveEdit() {
  saving.value = true
  editError.value = ''
  editSuccess.value = false
  try {
    const { data } = await candidatesApi.update(props.candidate.id, editForm)
    emit('updated', data)
    editSuccess.value = true
    setTimeout(() => editSuccess.value = false, 3000)
  } catch (err) {
    editError.value = err.response?.data?.error || 'Failed to save changes'
  } finally {
    saving.value = false
  }
}

const showDelete = ref(false)
const deleting = ref(false)

async function deleteCandidate() {
  deleting.value = true
  try {
    await candidatesApi.remove(props.candidate.id)
    emit('deleted', props.candidate.id)
    showDelete.value = false
  } catch (err) {
    console.error(err)
  } finally {
    deleting.value = false
  }
}

function close() { emit('update:modelValue', false) }

function formatDate(d) {
  if (!d) return '—'
  return new Date(d).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
}

function capitalize(s) { return s.charAt(0).toUpperCase() + s.slice(1) }
function scoreColor(s) {
  if (s >= 70) return 'text-green-600'
  if (s >= 40) return 'text-yellow-600'
  return 'text-red-500'
}
</script>

<!-- Helper component for read-only info fields -->
<script>
const InfoField = {
  props: { label: String, value: String },
  template: `
    <div>
      <p class="text-xs text-gray-400 mb-0.5">{{ label }}</p>
      <p class="text-sm text-gray-900 font-medium">{{ value || '—' }}</p>
    </div>
  `
}
export { InfoField }
</script>

// frontend/components/candidates/CandidateDrawer.tsx
'use client'

import { X, Phone, MapPin, Briefcase, Mail, Check, XCircle, Calendar, Edit2, Trash2, ChevronDown } from 'lucide-react'
import { Candidate, CandidateStatus } from '@/types'
import { AIScoreBadge } from './AIScoreBadge'
import { StatusBadge } from '@/components/shared/StatusBadge'
import { formatDate, formatDateTime } from '@/lib/utils'
import { useUpdateCandidate, useDeleteCandidate } from '@/hooks/useCandidates'
import { useIsAdmin, RoleGuard } from '@/components/shared/RoleGuard'
import { ConfirmDialog } from '@/components/shared/ConfirmDialog'
import { useState } from 'react'
import { toast } from 'sonner'
import { cn } from '@/lib/utils'

type Props = {
  candidate: Candidate | null
  open: boolean
  onClose: () => void
}

const statusOptions: { value: CandidateStatus; label: string }[] = [
  { value: 'pending', label: 'Pending' },
  { value: 'reviewed', label: 'Reviewed' },
  { value: 'called', label: 'Called' },
  { value: 'not_found', label: 'Not Found' },
  { value: 'processed_no_resume', label: 'No Resume' },
]

export function CandidateDrawer({ candidate, open, onClose }: Props) {
  const updateCandidate = useUpdateCandidate()
  const deleteCandidate = useDeleteCandidate()
  const isAdmin = useIsAdmin()
  const [confirmDelete, setConfirmDelete] = useState(false)

  if (!candidate) return null

  const handleStatusChange = async (status: CandidateStatus) => {
    try {
      await updateCandidate.mutateAsync({ id: candidate.id, data: { status } })
      toast.success('Status updated')
    } catch {
      toast.error('Failed to update status')
    }
  }

  const handleDelete = async () => {
    try {
      await deleteCandidate.mutateAsync(candidate.id)
      toast.success('Candidate deleted')
      setConfirmDelete(false)
      onClose()
    } catch {
      toast.error('Failed to delete candidate')
    }
  }

  const criteriaMet = candidate.aiCriteriaMet?.split('\n').filter(Boolean) ?? []
  const criteriaMissing = candidate.aiCriteriaMissing?.split('\n').filter(Boolean) ?? []

  return (
    <>
      {/* Backdrop */}
      {open && (
        <div
          className="fixed inset-0 z-40 bg-black/20 backdrop-blur-sm"
          onClick={onClose}
        />
      )}

      {/* Drawer */}
      <div
        className={cn(
          'fixed right-0 top-0 bottom-0 z-50 w-full max-w-xl bg-white shadow-2xl transition-transform duration-300 flex flex-col',
          open ? 'translate-x-0' : 'translate-x-full'
        )}
      >
        {/* Header */}
        <div className="flex items-start justify-between p-6 border-b border-slate-200">
          <div className="flex-1 min-w-0">
            <h2 className="text-lg font-bold text-slate-900 truncate">{candidate.candidateName}</h2>
            <div className="flex items-center gap-2 mt-1 flex-wrap">
              <StatusBadge status={candidate.status} />
              {candidate.aiRecommendation && (
                <StatusBadge status={candidate.aiRecommendation} />
              )}
            </div>
          </div>
          <button
            onClick={onClose}
            className="ml-4 p-1.5 text-slate-400 hover:text-slate-600 hover:bg-slate-100 rounded-lg transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto">
          {/* Basic info */}
          <div className="p-6 border-b border-slate-100 space-y-3">
            <div className="grid grid-cols-2 gap-3">
              <div className="flex items-start gap-2">
                <Briefcase className="w-4 h-4 text-slate-400 mt-0.5 flex-shrink-0" />
                <div>
                  <div className="text-xs text-slate-500">Posting</div>
                  <div className="text-sm font-medium text-slate-800">{candidate.postingName}</div>
                </div>
              </div>
              <div className="flex items-start gap-2">
                <MapPin className="w-4 h-4 text-slate-400 mt-0.5 flex-shrink-0" />
                <div>
                  <div className="text-xs text-slate-500">Location</div>
                  <div className="text-sm font-medium text-slate-800">{candidate.location}</div>
                </div>
              </div>
              {candidate.phone && (
                <div className="flex items-start gap-2">
                  <Phone className="w-4 h-4 text-slate-400 mt-0.5 flex-shrink-0" />
                  <div>
                    <div className="text-xs text-slate-500">Phone</div>
                    <div className="text-sm font-medium text-slate-800">{candidate.phone}</div>
                  </div>
                </div>
              )}
              <div className="flex items-start gap-2">
                <Mail className="w-4 h-4 text-slate-400 mt-0.5 flex-shrink-0" />
                <div>
                  <div className="text-xs text-slate-500">Email ID</div>
                  <code className="text-[11px] font-mono bg-slate-100 text-slate-600 px-1.5 py-0.5 rounded">
                    {candidate.emailId}
                  </code>
                </div>
              </div>
              {candidate.hiringManager && (
                <div>
                  <div className="text-xs text-slate-500">Hiring Manager</div>
                  <div className="text-sm font-medium text-slate-800">{candidate.hiringManager}</div>
                </div>
              )}
              {candidate.recruiter && (
                <div>
                  <div className="text-xs text-slate-500">Recruiter</div>
                  <div className="text-sm font-medium text-slate-800">{candidate.recruiter}</div>
                </div>
              )}
              {candidate.dateApplied && (
                <div className="flex items-start gap-2">
                  <Calendar className="w-4 h-4 text-slate-400 mt-0.5 flex-shrink-0" />
                  <div>
                    <div className="text-xs text-slate-500">Applied</div>
                    <div className="text-sm font-medium text-slate-800">{formatDate(candidate.dateApplied)}</div>
                  </div>
                </div>
              )}
            </div>

            {/* Status change */}
            <RoleGuard allowedRoles={['ADMIN', 'HR']}>
              <div className="pt-2">
                <label className="text-xs text-slate-500 mb-1.5 block">Change Status</label>
                <div className="relative">
                  <select
                    value={candidate.status}
                    onChange={(e) => handleStatusChange(e.target.value as CandidateStatus)}
                    className="w-full pl-3 pr-8 py-2 text-sm border border-slate-200 rounded-lg bg-white focus:outline-none focus:ring-2 focus:ring-blue-500/30 focus:border-blue-400 appearance-none"
                  >
                    {statusOptions.map((s) => (
                      <option key={s.value} value={s.value}>{s.label}</option>
                    ))}
                  </select>
                  <ChevronDown className="absolute right-2.5 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400 pointer-events-none" />
                </div>
              </div>
            </RoleGuard>
          </div>

          {/* AI Review */}
          {(candidate.aiScore !== undefined || candidate.aiSummary) && (
            <div className="p-6 border-b border-slate-100">
              <h3 className="text-sm font-semibold text-slate-900 mb-4">AI Review</h3>
              <div className="flex items-center gap-4 mb-4">
                <AIScoreBadge score={candidate.aiScore} size="lg" />
                <div>
                  <div className="text-xs text-slate-500 mb-1">Score</div>
                  {candidate.aiRecommendation && (
                    <StatusBadge status={candidate.aiRecommendation} />
                  )}
                </div>
                {candidate.reviewedAt && (
                  <div className="ml-auto text-right">
                    <div className="text-xs text-slate-400">Reviewed at</div>
                    <div className="text-xs text-slate-600">{formatDateTime(candidate.reviewedAt)}</div>
                  </div>
                )}
              </div>

              {criteriaMet.length > 0 && (
                <div className="mb-3">
                  <div className="text-xs font-medium text-green-700 mb-2">Criteria Met</div>
                  <ul className="space-y-1">
                    {criteriaMet.map((c, i) => (
                      <li key={i} className="flex items-start gap-2 text-xs text-slate-700">
                        <Check className="w-3.5 h-3.5 text-green-500 flex-shrink-0 mt-0.5" />
                        {c}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {criteriaMissing.length > 0 && (
                <div className="mb-3">
                  <div className="text-xs font-medium text-red-700 mb-2">Criteria Missing</div>
                  <ul className="space-y-1">
                    {criteriaMissing.map((c, i) => (
                      <li key={i} className="flex items-start gap-2 text-xs text-slate-700">
                        <XCircle className="w-3.5 h-3.5 text-red-400 flex-shrink-0 mt-0.5" />
                        {c}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {candidate.aiSummary && (
                <div className="mt-3 p-3 bg-slate-50 rounded-lg">
                  <div className="text-xs font-medium text-slate-600 mb-1">Summary</div>
                  <p className="text-xs text-slate-700 leading-relaxed">{candidate.aiSummary}</p>
                </div>
              )}
            </div>
          )}

          {/* Call / Transcript */}
          {(candidate.called || candidate.transcript) && (
            <div className="p-6 border-b border-slate-100">
              <h3 className="text-sm font-semibold text-slate-900 mb-3">Call Record</h3>
              {candidate.called && (
                <div className="flex items-center gap-2 mb-3">
                  <Phone className="w-4 h-4 text-slate-400" />
                  <span className="text-sm text-slate-700">{candidate.called}</span>
                </div>
              )}
              {candidate.transcript && (
                <div>
                  <div className="text-xs font-medium text-slate-600 mb-1.5">Transcript</div>
                  <div className="bg-slate-900 rounded-lg p-3 max-h-64 overflow-y-auto">
                    <pre className="text-xs text-slate-300 font-mono whitespace-pre-wrap leading-relaxed">
                      {candidate.transcript}
                    </pre>
                  </div>
                </div>
              )}
            </div>
          )}
        </div>

        {/* Footer actions */}
        <div className="p-4 border-t border-slate-200 flex items-center justify-between bg-white">
          <div className="text-xs text-slate-400">
            Created {formatDate(candidate.createdAt)}
          </div>
          <div className="flex items-center gap-2">
            <RoleGuard allowedRoles={['ADMIN', 'MANAGER', 'HR']}>
              <button className="flex items-center gap-1.5 px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-100 rounded-lg transition-colors border border-slate-200">
                <Edit2 className="w-3.5 h-3.5" />
                Edit
              </button>
            </RoleGuard>
            <RoleGuard allowedRoles={['ADMIN']}>
              <button
                onClick={() => setConfirmDelete(true)}
                className="flex items-center gap-1.5 px-3 py-2 text-sm font-medium text-red-600 hover:bg-red-50 rounded-lg transition-colors border border-red-200"
              >
                <Trash2 className="w-3.5 h-3.5" />
                Delete
              </button>
            </RoleGuard>
          </div>
        </div>
      </div>

      <ConfirmDialog
        open={confirmDelete}
        onOpenChange={setConfirmDelete}
        title="Delete Candidate"
        description={`Are you sure you want to delete ${candidate.candidateName}? This action cannot be undone.`}
        confirmLabel="Delete"
        onConfirm={handleDelete}
        isLoading={deleteCandidate.isPending}
      />
    </>
  )
}
