// frontend-vue/src/components/layout/Topbar.vue
<template>
  <header class="bg-white border-b border-gray-200 px-4 py-3 flex items-center justify-between flex-shrink-0">
    <!-- Mobile hamburger -->
    <button
      class="lg:hidden p-2 rounded-lg text-gray-500 hover:bg-gray-100 hover:text-gray-700 transition-colors"
      @click="$emit('toggle-sidebar')"
    >
      <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
      </svg>
    </button>

    <!-- Page title -->
    <h1 class="text-lg font-semibold text-gray-900 lg:ml-0 ml-2">{{ pageTitle }}</h1>

    <!-- Right side -->
    <div class="flex items-center gap-3">
      <span class="hidden sm:inline-flex badge bg-brand-100 text-brand-800">
        {{ auth.user?.role }}
      </span>
      <div class="w-8 h-8 rounded-full bg-brand-500 flex items-center justify-center">
        <span class="text-xs font-semibold text-white">{{ userInitials }}</span>
      </div>
    </div>
  </header>
</template>

<script setup>
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import { useAuthStore } from '@/stores/auth'

defineEmits(['toggle-sidebar'])

const auth = useAuthStore()
const route = useRoute()

const pageTitles = {
  '/dashboard': 'Dashboard',
  '/candidates': 'Candidates',
  '/appointments': 'Appointments',
  '/availability': 'Availability',
  '/users': 'User Management',
}

const pageTitle = computed(() => {
  if (route.name === 'CandidateDetail') return 'Candidate Detail'
  return pageTitles[route.path] || 'TalentFlow'
})

const userInitials = computed(() => {
  if (!auth.user?.name) return '?'
  return auth.user.name.split(' ').map(n => n[0]).join('').toUpperCase().slice(0, 2)
})
</script>

// frontend/components/layout/Topbar.tsx
'use client'

import { usePathname } from 'next/navigation'
import { Bell, ChevronRight } from 'lucide-react'
import { useSession } from 'next-auth/react'
import { useRole } from '@/components/shared/RoleGuard'
import { cn } from '@/lib/utils'
import { Role } from '@/types'

const pageLabels: Record<string, string> = {
  dashboard: 'Dashboard',
  candidates: 'Candidates',
  appointments: 'Appointments',
  availability: 'Availability',
  users: 'User Management',
}

const roleBadge: Record<Role, string> = {
  ADMIN: 'bg-red-50 text-red-700 ring-red-200',
  MANAGER: 'bg-blue-50 text-blue-700 ring-blue-200',
  HR: 'bg-emerald-50 text-emerald-700 ring-emerald-200',
}

export function Topbar() {
  const pathname = usePathname()
  const { data: session } = useSession()
  const role = useRole()

  const segments = pathname.split('/').filter(Boolean)
  const crumbs = segments.map((seg, i) => ({
    label: pageLabels[seg] ?? seg.replace(/-/g, ' '),
    href: '/' + segments.slice(0, i + 1).join('/'),
    isLast: i === segments.length - 1,
  }))

  const pageTitle = crumbs[crumbs.length - 1]?.label ?? 'Dashboard'

  return (
    <header className="h-14 bg-white border-b border-slate-200 flex items-center justify-between px-6 sticky top-0 z-20">
      <div>
        <div className="flex items-center gap-1.5 text-xs text-slate-400 mb-0.5">
          <span>Home</span>
          {crumbs.map((c) => (
            <span key={c.href} className="flex items-center gap-1.5">
              <ChevronRight className="w-3 h-3" />
              <span className={cn(c.isLast ? 'text-slate-700 font-medium' : 'text-slate-400')}>
                {c.label}
              </span>
            </span>
          ))}
        </div>
        <h1 className="text-base font-semibold text-slate-900">{pageTitle}</h1>
      </div>

      <div className="flex items-center gap-3">
        <button className="relative p-2 text-slate-400 hover:text-slate-600 hover:bg-slate-100 rounded-lg transition-colors">
          <Bell className="w-4 h-4" />
          <span className="absolute top-1.5 right-1.5 w-1.5 h-1.5 rounded-full bg-blue-500" />
        </button>

        <div className="flex items-center gap-2.5 pl-3 border-l border-slate-200">
          <div className="w-7 h-7 rounded-full bg-slate-800 flex items-center justify-center">
            <span className="text-[11px] font-bold text-white">
              {session?.user?.name?.charAt(0)?.toUpperCase() ?? '?'}
            </span>
          </div>
          <div className="hidden sm:block">
            <div className="text-xs font-medium text-slate-900 leading-none mb-0.5">
              {session?.user?.name}
            </div>
            {role && (
              <span className={cn('text-[10px] font-semibold px-1.5 py-0.5 rounded-full ring-1 ring-inset uppercase tracking-wide', roleBadge[role])}>
                {role}
              </span>
            )}
          </div>
        </div>
      </div>
    </header>
  )
}
